calorie_tracker/urls.py
from django.urls import path
from . import views
from .views import (
    DashboardView,
    ProfileDetailView,
    ProfileUpdateView,
    FoodDetailView,
    FoodDayView,
    FoodCalendarWeekView,
    FoodRollingWeekView,
    FoodCreateView,
    FoodUpdateView,
    FoodDeleteView,
    CardioDetailView,
    CardioDayView,
    CardioCalendarWeekView,
    CardioRollingWeekView,
    CardioCreateView,
    CardioUpdateView,
    CardioDeleteView,
)

app_name = 'calorie_tracker'

urlpatterns = [
    # Overview URLS

    path('', DashboardView.as_view(), name='home'),
    path(
        'calendar-week-summary/', views.calendar_week_summary,
        name='calendar_week_summary'),
    path(
        'rolling-week-summary/',
        views.rolling_week_summary,
        name='rolling_week_summary'),

    # User profile URLS

    path('profile/', ProfileDetailView.as_view(), name='profile_detail'),
    path('profile/update', ProfileUpdateView.as_view(), name='profile_update'),

    # Food URLS

    path('food/', FoodDayView.as_view(), name='food_day'),
    path('food/add/', FoodCreateView.as_view(), name='add_food'),

    path('food/<int:pk>/', FoodDetailView.as_view(), name='food_detail'),
    path(
        'food/<int:pk>/update/',
        FoodUpdateView.as_view(),
        name="update_food"),
    path(
        'food/<int:pk>/delete/',
        FoodDeleteView.as_view(),
        name="delete_food"),
    path(
        'food/week/calendar/',
        FoodCalendarWeekView.as_view(),
        name='food_calendar_week'),
    path(
        'food/week/rolling/',
        FoodRollingWeekView.as_view(),
        name='food_rolling_week'),

    # Cardio URLS

    path(
        'cardio/', CardioDayView.as_view(), name='cardio_day'),
    path(
        'cardio/add/', CardioCreateView.as_view(), name='add_cardio'),

    path(
        'cardio/<int:pk>/',
        CardioDetailView.as_view(),
        name='cardio_detail'),
    path(
        'cardio/<int:pk>/update/',
        CardioUpdateView.as_view(),
        name="update_cardio"),
    path(
        'cardio/<int:pk>/delete/',
        CardioDeleteView.as_view(),
        name="delete_cardio"),
    path(
        'cardio/week/calendar/',
        CardioCalendarWeekView.as_view(),
        name='cardio_calendar_week'),
    path(
        'cardio/week/rolling/',
        CardioRollingWeekView.as_view(),
        name='cardio_rolling_week'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from calorie_tracker.views import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path(
        '',
        DashboardView.as_view(),
        name='home'
        ),
    path(
        'tracker/',
        include(
            ('calorie_tracker.urls', 'calorie_tracker'),
            namespace='calorie_tracker')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    # Add Debug Toolbar URLs
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% if page_title %}
                {{ page_title }} - Calorie Tracker
            {% else %}
                Calorie Tracker
            {% endif %}
        </title>
        <link rel="stylesheet" href="{% static 'css/calorie_tracker.css' %}">
    </head>
    <body>
        <header class="header">
            {% if page_title %}
                <h1>{{ page_title }}</h1>
            {% else %}
                <h1>Calorie Tracker</h1>
            {% endif %}
            <nav>
                {% if user.is_authenticated %}
                    <a href="{% url 'calorie_tracker:home' %}">Dashboard</a> |
                    <a href="{% url 'calorie_tracker:add_food' %}">Add Food</a> |
                    <a href="{% url 'calorie_tracker:add_cardio' %}">Add Cardio</a> |
                    <a href="{% url 'calorie_tracker:profile_detail' %}">Profile</a> |
                    <a href="{% url 'calorie_tracker:profile_update' %}">Update Goals</a> |
                    <a href="{% url 'account_logout' %}">Logout ({{ user.username }})</a>
                {% else %}
                    <a href="{% url 'account_login' %}">Login</a> |
                    <a href="{% url 'account_signup' %}">Register</a>
                {% endif %}
            </nav>
            <hr />
        </header>
        <div class="site-wrap">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    <h2>Welcome to Calorie Tracker</h2>
    <p>Track your food and cardio activity here.</p>
{% endblock %}